Tests

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -19,13 +19,36 @@ jobs:
         host: ${{ secrets.SSH_HOST }}
         username: ${{ secrets.SSH_USER }}
         password: ${{ secrets.SSH_PASSWORD }}
+        script_stop: true
         script: |
+          set -e
+
+          # Vérifier les versions de Node.js et npm
+          echo "Node.js version: $(node -v)"
+          echo "npm version: $(npm -v)"
+          
+          # Cloner le dépôt
           git clone https://github.com/eliooooooo/Book.git
           if [ ! -d "www" ]; then
             mkdir www
           fi
+          
+          # Copier les fichiers et changer de répertoire
           cp -r Book/* www
           rm -rf Book
           cd www
-          npm install
-          npm run prod
+
+          # Afficher les fichiers et permissions dans le répertoire www avant l'installation
+          echo "Contenu du répertoire www avant l'installation:"
+          ls -l
+          
+          # Installer les dépendances
+          npm ci
+          
+          # Afficher les fichiers et permissions dans le répertoire www après l'installation
+          echo "Contenu du répertoire www après l'installation:"
+          ls -l
+
+          # Exécuter npm run prod et capturer les erreurs
+          echo "Exécution de npm run prod:"
+          npm run prod 2>error.log || { echo 'npm run prod failed'; cat error.log; exit 1; }
